services:
  anonymous_bot:
    build: .
    restart: unless-stopped
    depends_on:
      - anonymous_bot_postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: anonymous_bot_postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
  anonymous_bot_postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - anonymous_bot_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  anonymous_bot_postgres:
